### ISSUE TITLE
Better failure handling in offline profiler

### ISSUE THREAD

**Issue by Romero027** [UWNetworksLab/meshinsight#1]

**Comment by arjuntemura** [comment]
Hi @Romero027 
I was getting 'nan' values for read and write components of TCP, HTTP, and gRPC traffic while running the offline profiler.  
I tried the following with a tcp workload of 100 bytes

`
13-Jul-23 13:01:32 |     INFO | Latency profiling finished!
13-Jul-23 13:01:32 |     INFO | Profile saved to /home/ryzen02/meshinsight/meshinsight/profiles/profile.pkl
{('CPU: AMD Ryzen 9 5950X 16-Core Processor', 'Kernel: 4.15.0-212-generic', 'Kubernetes: Client Version', 'Istio: v1.18.0'): {'latency': {'tcp': {100: {'read': nan, 'write': nan, 'ipc': 13.59, 'epoll': 2.0, 'others(proxy)': 264.36}}}}}
13-Jul-23 13:01:52 |     INFO | Profile finished, took 396.81 seconds
`
